"""Fix typo error in column name 'update_at' to 'updated_at'

Revision ID: 131fef43bc54
Revises: 1d8216a664e9
Create Date: 2024-05-04 10:34:20.991768

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "131fef43bc54"
down_revision = "1d8216a664e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Comment", schema=None) as batch_op:
        pass
        # Drop the existing column
        #  batch_op.drop_column("updated_at")

        # Add the new column
        #  batch_op.add_column(sa.Column("updated_at", sa.Text(), nullable=False))


#         batch_op.alter_column(
#             "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
#         )
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "post_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "replied_comment_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("CommentLike", schema=None) as batch_op:
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "comment_id ",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("CommentNotification", schema=None) as batch_op:
#         batch_op.alter_column(
#             "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
#         )
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "comment_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "unread_comment_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("Post", schema=None) as batch_op:
#         batch_op.alter_column(
#             "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
#         )
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("PostBookmark", schema=None) as batch_op:
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "post_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("PostLike", schema=None) as batch_op:
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "post_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("PostNotification", schema=None) as batch_op:
#         batch_op.alter_column(
#             "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
#         )
#         batch_op.alter_column(
#             "user_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "post_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "unread_comment_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("PostTag", schema=None) as batch_op:
#         batch_op.alter_column(
#             "post_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )
#         batch_op.alter_column(
#             "tag_id",
#             existing_type=sa.NUMERIC(),
#             type_=sa.UUID(),
#             existing_nullable=True,
#         )

#     with op.batch_alter_table("Tag", schema=None) as batch_op:
#         batch_op.alter_column(
#             "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
#         )

#     with op.batch_alter_table("User", schema=None) as batch_op:
#         batch_op.alter_column(
#             "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
#         )

# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("Tag", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("PostTag", schema=None) as batch_op:
        batch_op.alter_column(
            "tag_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "post_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )

    with op.batch_alter_table("PostNotification", schema=None) as batch_op:
        batch_op.alter_column(
            "unread_comment_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "post_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("PostLike", schema=None) as batch_op:
        batch_op.alter_column(
            "post_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )

    with op.batch_alter_table("PostBookmark", schema=None) as batch_op:
        batch_op.alter_column(
            "post_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )

    with op.batch_alter_table("Post", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("CommentNotification", schema=None) as batch_op:
        batch_op.alter_column(
            "unread_comment_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "comment_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("CommentLike", schema=None) as batch_op:
        batch_op.alter_column(
            "comment_id ",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )

    with op.batch_alter_table("Comment", schema=None) as batch_op:
        batch_op.alter_column(
            "replied_comment_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "post_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    # ### end Alembic commands ###
