"""empty message

Revision ID: 195cfb04d4e2
Revises: 
Create Date: 2024-06-02 19:49:33.886392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195cfb04d4e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('Comment_replied_comment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Comment_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Comment_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Comment', ['replied_comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('CommentLike', schema=None) as batch_op:
        batch_op.drop_constraint('CommentLike_comment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('CommentLike_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Comment', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('CommentNotification_unread_comment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('CommentNotification_comment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('CommentNotification_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Comment', ['unread_comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Comment', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('Post_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
        batch_op.drop_constraint('PostBookmark_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('PostBookmark_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('PostLike', schema=None) as batch_op:
        batch_op.drop_constraint('PostLike_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('PostLike_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('PostNotification', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('PostNotification_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('PostNotification_unread_comment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('PostNotification_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Comment', ['unread_comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('PostTag', schema=None) as batch_op:
        batch_op.drop_constraint('PostTag_tag_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('PostTag_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tag', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('PostTag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('PostTag_post_id_fkey', 'Post', ['post_id'], ['id'])
        batch_op.create_foreign_key('PostTag_tag_id_fkey', 'Tag', ['tag_id'], ['id'])

    with op.batch_alter_table('PostNotification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('PostNotification_post_id_fkey', 'Post', ['post_id'], ['id'])
        batch_op.create_foreign_key('PostNotification_unread_comment_id_fkey', 'Comment', ['unread_comment_id'], ['id'])
        batch_op.create_foreign_key('PostNotification_user_id_fkey', 'User', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('PostLike', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('PostLike_post_id_fkey', 'Post', ['post_id'], ['id'])
        batch_op.create_foreign_key('PostLike_user_id_fkey', 'User', ['user_id'], ['id'])

    with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('PostBookmark_post_id_fkey', 'Post', ['post_id'], ['id'])
        batch_op.create_foreign_key('PostBookmark_user_id_fkey', 'User', ['user_id'], ['id'])

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Post_user_id_fkey', 'User', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('CommentNotification_user_id_fkey', 'User', ['user_id'], ['id'])
        batch_op.create_foreign_key('CommentNotification_comment_id_fkey', 'Comment', ['comment_id'], ['id'])
        batch_op.create_foreign_key('CommentNotification_unread_comment_id_fkey', 'Comment', ['unread_comment_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('CommentLike', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('CommentLike_user_id_fkey', 'User', ['user_id'], ['id'])
        batch_op.create_foreign_key('CommentLike_comment_id_fkey', 'Comment', ['comment_id'], ['id'])

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Comment_post_id_fkey', 'Post', ['post_id'], ['id'])
        batch_op.create_foreign_key('Comment_user_id_fkey', 'User', ['user_id'], ['id'])
        batch_op.create_foreign_key('Comment_replied_comment_id_fkey', 'Comment', ['replied_comment_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
