"""empty message

Revision ID: 41d4b7440727
Revises: b9c98406f9b9
Create Date: 2024-05-06 10:20:08.415003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d4b7440727'
down_revision = 'b9c98406f9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Comment", schema=None) as batch_op:
        # Drop the existing column
         batch_op.drop_column("update_at")

        # Add the new columnpyt
         batch_op.add_column(sa.Column("updated_at", sa.Text(), nullable=False))
    
#     with op.batch_alter_table('Comment', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('replied_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('CommentLike', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('comment_id ',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('unread_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('Post', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostLike', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostNotification', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('unread_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostTag', schema=None) as batch_op:
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('tag_id',
#                existing_type=sa.NUMERIC()
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('Tag', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)

#     with op.batch_alter_table('User', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('PostTag', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('PostNotification', schema=None) as batch_op:
        batch_op.alter_column('unread_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('PostLike', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
        batch_op.alter_column('unread_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('CommentLike', schema=None) as batch_op:
        batch_op.alter_column('comment_id ',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.alter_column('replied_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_Comment',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('is_report', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('update_at', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=True),
    sa.Column('post_id', sa.NUMERIC(), nullable=True),
    sa.Column('replied_comment_id', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['replied_comment_id'], ['Comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
