"""empty message

Revision ID: 73a4a905d845
Revises: 3876540ba8e3
Create Date: 2024-04-27 09:51:22.435532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a4a905d845'
down_revision = '3876540ba8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yoo', sa.VARCHAR(length=60), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('anon_no', sa.VARCHAR(length=4), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('campus', sa.VARCHAR(length=9), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
