"""empty message

Revision ID: 8cddbae2291b
Revises: 131fef43bc54
Create Date: 2024-05-06 10:06:10.967332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cddbae2291b'
down_revision = '131fef43bc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
#     drop table _alembic_tmp_Comment
#     op.drop_table('_alembic_tmp_Comment')

       with op.batch_alter_table("Comment", schema=None) as batch_op:
              # Drop the existing column
              batch_op.drop_column("updated_at")

              # Add the new column
              batch_op.add_column(sa.Column("updated_at", sa.Text(), nullable=False))

    
#     with op.batch_alter_table('Comment', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('updated_at', sa.Text(), nullable=False))
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('replied_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.drop_column('update_at')

#     with op.batch_alter_table('CommentLike', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('comment_id ',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('unread_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('Post', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('updated_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostLike', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostNotification', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('unread_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostTag', schema=None) as batch_op:
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('tag_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('Tag', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('updated_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.create_unique_constraint('name', ['name'])

#     with op.batch_alter_table('User', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('updated_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('PostTag', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('PostNotification', schema=None) as batch_op:
        batch_op.alter_column('unread_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('PostLike', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
        batch_op.alter_column('unread_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('CommentLike', schema=None) as batch_op:
        batch_op.alter_column('comment_id ',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('replied_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
