"""aaaaa

Revision ID: b32f97d14c2c
Revises: 9dcc1ed4d2a9
Create Date: 2024-05-02 10:24:15.253124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32f97d14c2c'
down_revision = '9dcc1ed4d2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Comment')
#     op.drop_table('_alembic_tmp_Post')
#     with op.batch_alter_table('Comment', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('update_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('replied_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('CommentLike', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('comment_id ',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('unread_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('Post', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('updated_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostLike', schema=None) as batch_op:
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostNotification', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('unread_comment_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('PostTag', schema=None) as batch_op:
#         batch_op.alter_column('post_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#         batch_op.alter_column('tag_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)

#     with op.batch_alter_table('Tag', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('updated_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.create_unique_constraint(None, ['name'])

#     with op.batch_alter_table('User', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#         batch_op.alter_column('created_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)
#         batch_op.alter_column('updated_at',
#                existing_type=sa.DATETIME(),
#                type_=sa.Text(),
#                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_User')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('Tag', schema=None) as batch_op:
       #  batch_op.drop_constraint('constraint_name', type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('PostTag', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('PostNotification', schema=None) as batch_op:
        batch_op.alter_column('unread_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('PostLike', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('PostBookmark', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('CommentNotification', schema=None) as batch_op:
        batch_op.alter_column('unread_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('CommentLike', schema=None) as batch_op:
        batch_op.alter_column('comment_id ',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.alter_column('replied_comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_Comment',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('is_report', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('update_at', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=True),
    sa.Column('post_id', sa.NUMERIC(), nullable=True),
    sa.Column('replied_comment_id', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], name='fk_post_id'),
    sa.ForeignKeyConstraint(['replied_comment_id'], ['Comment.id'], name='fk_replied_comment_id'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_user_id'),
    sa.PrimaryKeyConstraint('id', name='pk_comment_id')
    )
    # ### end Alembic commands ###
